# 端口
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/market2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: "1584327hqq"
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    com.market: debug